getwd()
setwd("~/Desktop/Data Sience Course")
hpc <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
View(hpc)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc$DateTime <- strptime(paste(hpc$Date, hpc$Time), format = "%Y-%m-%d %H:%M:%S")
subhpc <- subset(hpc, hpc$Date>="2007-02-01" & hpc$Date <= "2007-02-02")
View(subhpc)
png("plot1.png",width=480,height=480)
hist(as.numeric(subhpc$Global_active_power), col = "red", main = "Global Active Power", xlab = "Global Active Power(kilowatts)")
dev.off()