getwd()
setwd("~/Desktop/Data Sience Course")
hpc <- read.csv("household_power_consumption.txt", sep=";", stringsAsFactors = FALSE)
View(hpc)
hpc$Date <- as.Date(hpc$Date, format = "%d/%m/%Y")
hpc$DateTime <- strptime(paste(hpc$Date, hpc$Time), format = "%Y-%m-%d %H:%M:%S")
subhpc <- subset(hpc, hpc$Date>="2007-02-01" & hpc$Date <= "2007-02-02")
View(subhpc)
png("plot3.png",width=480,height=480)
plot(as.numeric(subhpc$DateTime), as.numeric(subhpc$Sub_metering_1),type="l",xaxt="n",xlab="",ylab="Energy sub metering")
axis(side = 1, at= c(as.numeric(subhpc$DateTime[1]), as.numeric(subhpc$DateTime[1440]), as.numeric(subhpc$DateTime[2880])), labels = c("Thu","Fri","Sat"))
lines(as.numeric(subhpc$DateTime), as.numeric(subhpc$Sub_metering_2), col="red")
lines(as.numeric(subhpc$DateTime), as.numeric(subhpc$Sub_metering_3), col="blue")
legend("topright",col=c("black","red","blue"), c("Sub_metering_1","Sub_metering_2", "Sub_metering_3"), lty=1)
dev.off()
